In [4]:
import numpy as np

In [ ]:
menu=np.array(['cheese','bbq','veg','spicy'])
print(menu)

['cheese' 'bbq' 'spicy']


In [3]:
prices=[100,200,150,120]
prices * 0.8

TypeError: can't multiply sequence by non-int of type 'float'

In [7]:
prices_np=np.array([100,200,150,120])
discounted =prices_np * 0.8
print(discounted)

[ 80. 160. 120.  96.]


In [4]:
empty_tables= np.zeros((2,3))
print("Empty Tables : \n",empty_tables)

Empty Tables : 
 [[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
full_tables= np.ones((2,3))
print("Full Tables : \n",full_tables)

Full Tables : 
 [[1. 1. 1.]
 [1. 1. 1.]]


In [6]:
bbq_box=np.full((2,3),'BBQ')
print("Now Tables is : \n",bbq_box)

Now Tables is : 
 [['BBQ' 'BBQ' 'BBQ']
 ['BBQ' 'BBQ' 'BBQ']]


In [7]:
bbq_box[1,1:]="VEG"
print(bbq_box)

[['BBQ' 'BBQ' 'BBQ']
 ['BBQ' 'VEG' 'VEG']]


In [16]:
surprise_toppings=np.random.rand(2,3)
print("Random Surprise Toppings : \n",surprise_toppings)

Random Surprise Toppings : 
 [[0.49175221 0.9609099  0.25275797]
 [0.58128261 0.97498558 0.90287473]]


In [17]:
kids_order=np.random.randint(1,8,(3,2))
print("Kids Slice orders : \n",kids_order)

Kids Slice orders : 
 [[3 7]
 [3 6]
 [1 1]]


In [18]:
singnature_pizzas=np.identity(3)
print("Signature Pizzas Tables : \n",singnature_pizzas)

Signature Pizzas Tables : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
singnature_pizzas=np.identity(3)
singnature_pizzas=singnature_pizzas.astype(int)
print("Signature Pizzas Tables : \n",singnature_pizzas)
print(type(singnature_pizzas))

Signature Pizzas Tables : 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
<class 'numpy.ndarray'>


In [19]:
delivary_times=np.arange(0,120,15)
print(delivary_times)

[  0  15  30  45  60  75  90 105]


In [20]:
cooking_shifts=np.linspace(0,60,6)
print(cooking_shifts)


[ 0. 12. 24. 36. 48. 60.]


In [23]:
orders=np.array(['cheese','veg','spicy','bbq'])
print(orders[1:3])

['veg' 'spicy']


In [7]:
orders=np.array([
    ['cheese','veg'],
    ['spicy','bbq ']
])
print(orders[0,1])

veg


In [8]:
print(orders[1,:])

['spicy' 'bbq ']


In [9]:
print(orders[:,0])

['cheese' 'spicy']


In [10]:
sales=np.array([1200,1500,900,2000])
print("Max sales : ",np.max(sales))

Max sales :  2000


In [11]:
print("Best Seller : ",np.argmax(sales))

Best Seller :  3


In [12]:
print("Worst Seller : ",np.argmin(sales))

Worst Seller :  2
